### PR TITLE
Add careers pages

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Add career pages

## QA
- Go to [/careers/design](http://0.0.0.0:8002/careers/design) and navigate to all other pages.
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1535)
- Make sure the tab navigation is functional
- Make sure the navigation on the left is functional (note that there are no pages created for lifestyle, ethics, etc.)

## Issue

Fixes https://github.com/canonical-web-and-design/web-squad/issues/1535

### CODE REVIEW

**Comment by anthonydillon** [comment]
Code looks good, QA points:
- The side navigation looks like to could do with more padding between items. Could you use `p-list` and `p-list__item` to space them out?

**Comment by anthonydillon** [comment]
The first paragraph should be bold.

**Comment by anthonydillon** [comment]
The highlight on the tabs component is orange

**Comment by anthonydillon** [comment]
Looks like the:
Emea | Americas
Apply now ›
 is to close to the footer

**Comment by anthonydillon** [comment]
On small screens, changing the drop down does not update the page.

**Comment by waynecrosby** [comment]
Add space in between the 2 filters, currently touching.

**Comment by waynecrosby** [comment]
Send CV:
Add space above the title
Add space after the form to make more space between the footer and form
Remove thin border from form background
Add (*Required) for the indicated fields

**Comment by solazio** [comment]
> Add space in between the 2 filters, currently touching.

@waynecrosby this will be fixed in a separate PR dedicated to that section

**Comment by solazio** [comment]
> On small screens, changing the drop down does not update the page.

@anthonydillon this will be fixed in a future PR which I will create after I merge this one.

**Comment by solazio** [comment]
> Code looks good, QA points:
> 
> * The side navigation looks like to could do with more padding between items. Could you use `p-list` and `p-list__item` to space them out?

@anasereijo I didn't use those clases because I have something more specific, but I added the same spacing.

**Pull request merged**
