### PR TITLE
Code cleanup

### LINKED ISSUE #341: H1 is duplicated on career listing pages
Screenshot 2021-02-04 at 15 57 58

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

- Update README to include info on API key
- Add Prettier as a dep
- Run Prettier over whole site
- Fix invalid HTML

## QA

Note: Due to Prettier, it'll be easier to review code by following commits

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Sanity check code
- Verify all tests and checks pass

### CODE REVIEW

**Comment by anthonydillon** [comment]
Nice one, is there any way to catch headings with `<strong>` elements as they seem common:
- https://canonical-com-342.demos.haus/careers/2441153

Also what about h1's:
- https://canonical-com-342.demos.haus/careers/2612092

Could you grab assets from the careers Twitter account for the social stuff?
https://twitter.com/ubuntuwantsyou

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Some questions/requests in the comment above

**Comment by barrymcgee** [comment]
@anthonydillon Both of your examples would miss anyway as the actual job title string between the two differ, which convinces me that this approach is too fragile. I still don't understand why the title needs to be in the description in Greenhouse? Surely the proper fix is to resolve at source?

Wayne is sorting an appropriate asset for the OpenGraph tags.

**Comment by anthonydillon** [comment]
Oh yes I see. You are right, this is not the right solution.

**Comment by barrymcgee** [comment]
@anthonydillon I've removed the commit related to hiding the titles. The rest of the changeset should be good to land and I'll follow up on the issue of the duplicate title separately.

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Pull request merged**
