### PR TITLE
Bump cookie policy to  v3.03

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Bump cookie policy to  v3.03
- Update GTM to track initial pageview

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that you are using cookie policy 3.03

### CODE REVIEW

**Review by anthonydillon — CHANGES_REQUESTED** [review]
The cookie-policy is missing when built:
``` html
<script src="/static/js/modules/cookie-policy/cookie-policy.js?v=file-not-found"></script>
```

**Comment by pmahnke** [comment]
strange - I see it - 
image

**Comment by pmahnke** [comment]
@anthonydillon it was the Dockerfile... arg... fixed

**Review by anthonydillon — APPROVED** [review]
LGTM :+1: nice spot

**Comment by anthonydillon** [comment]
Merging as its 3.0.2 -> 3.0.3

**Pull request merged**
