### PR TITLE
Reduce parsing of department fields

### PR DESCRIPTION
**Pull request by MeltySnow**
## Details

- Follow up to https://github.com/canonical-web-and-design/canonical.com/pull/273; don't review or merge this before that one is merged.
- It was previously discussed that it would be good to minimise the use of logic and field mapping in middleware and try to use data straight from the Harvest API as much as possible.<details>image</details>
- I apologise for the format and timing of this PR; I would have like to wait for #273 to be merged before pushing this up, but as I am leaving the company today I thought it might be worth pushing this up so you have the option to take it or leave it as you wish.

## Done

- Removed the `__parse_feed_department` function from the `Department` class in `app.py`
- Reduced the number of fields in the `_parse_feed_department` function in `greenhouse.py`
- Renamed several files in `/templates/careers` to match the department names on the Harvest API

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/all
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Ensure that all department fields are present in the navigation (I believe there should be 12 at this time)
- Ensure that the vacancy counters in the navigation, as well as the number of vacancies that actually show up, are still accurate
- Ensure that all departments that have corresponding templates actually render properly instead of the generic placeholder (I believe this should be all departments except for `/careers/product`)

### CODE REVIEW

**Comment by SirSamTumless** [comment]
@jkfran Do you have time to review this in the current iteration?

**Comment by jkfran** [comment]
> @jkfran Do you have time to review this in the current iteration?

This can't be merged until #273 is merged, the blocker for both PRs is because IS has to allow connections to a new API, there is an RT currently open for this.

I will review it when it's done but it might be next iteration because of the open RT.

**Comment by carkod** [comment]
I think this is the [RT](https://portal.admin.canonical.com/C127400/) they don't seem to be working on this, they usually need a priority level.

**Comment by jkfran** [comment]
> I think this is the [RT](https://portal.admin.canonical.com/C127400/) they don't seem to be working on this, they usually need a priority level.

Yes, I am not able to prioritize the ticket: "Since you have 3 prioritized ticket(s) you cannot mark more tickets as prioritized. ",  the 3 prioritized tickets are from the webteam and not just mine, I am not sure if this is more important than any of the other three, maybe @nottrobin can help us with this?

**Comment by nottrobin** [comment]
All the tickets currently prioritised are kind of important. Do we know the priority on this? Is it urgent?

**Comment by jkfran** [comment]
> All the tickets currently prioritised are kind of important. Do we know the priority on this? Is it urgent?

They complete it today! So this is no longer block by IS but we should merge the other PR first, I will help with that.

**Comment by jkfran** [comment]
@anthonydillon Ant, could you review and QA as I had to do some changes?

Some careers URLs are going to change now, is that fine? should we redirect?

**Review by anthonydillon — APPROVED** [review]
LGTM :+1: good stuff, sorry took a while.

**Pull request merged**
