### PR TITLE
Reformat; sort by core-skills

### PR DESCRIPTION
**Pull request by nottrobin**
QA
==

Thoroughly QA the whole careers section please =) https://canonical-com-358.demos.haus/careers

### CODE REVIEW

**Comment by pmahnke** [comment]
@nottrobin the game doesn't seem to work?  I see the 'slug' is there.

**Comment by anthonydillon** [comment]
## QA issues:
- The title of the page is missing the job title: https://canonical-com-358.demos.haus/careers/2675962/engineering-manager-telco-remote
- The application form at the bottom is missing a bunch of fields

**Comment by nottrobin** [comment]
@anthonydillon I fixed those. Would you mind testing all the way through to submitting an application? (Peter says to use https://canonical-com-358.demos.haus/careers/2544446/senior-ux-designer--remote, and Claudio will delete it - thanks @clagom)

**Comment by anthonydillon** [comment]
Thanks, done. 

@clagom can you check you get an "Anthony Dillon" submission. I'll filled in all fields so should have something in all fields.

**Review by pmahnke — APPROVED** [review]
+1 I tested and saw an application make it through.

**Pull request merged**
