### PR TITLE
Add github workflows

### LINKED ISSUE #287: Move to GitHub Actions

### PR DESCRIPTION
**Pull request by carkod**
## Done

- Github checks

## QA

- All Github checks should pass

## Issue / Card

Fixes #287

### CODE REVIEW

**Comment by jkfran** [comment]
@carkod Nice, can we remove the `circleci/config.yml` file?

**Comment by carkod** [comment]
> @carkod Nice, can we remove the `.circleci/config.yml` file?

Yes, I will do it later when I am sure the github checks are working.

**Review by jkfran — APPROVED** [review]
Cool! 👍🏻

**Comment by jkfran** [comment]
@carkod Unlink the project on the circleci website.

**Pull request merged**
