### PR TITLE
Update canonical logo banner

### PR DESCRIPTION
**Pull request by minkyngkm**
## Done

- Update ubuntu icon and add "Canonical" in the logo section

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes [#4790](https://github.com/canonical-web-and-design/web-squad/issues/4790)

## Screenshots

image

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
couple of things:

- grey bar above the logo on some screen sizes:
image

- would be nice if we can align the menu items on mobile under the wordmark. Compare with the design of u.c:
image

On other sites, the "Canonical" dropdown seems clear - other stuff by Canonical. But is this clear on the actual Canonical site? Why not call it "Products"? CC @davegoddard42

**Comment by davegoddard42** [comment]
@lyubomir-popov - valid point. I want it to have the same name across all sites, so it has familiarity and learnability. My current thinking is to call it "All Canonical" - this is a terminology I have seen elsewhere, and it means more than just products can reside there once we revamp the content within it.

**Comment by sowasred2012** [comment]
@lyubomir-popov @davegoddard42 I take the point about aligning the items with the logo text on mobile, but using the current navigation pattern, I'm not sure how to tweak it to also fit with the active state. Perhaps the active indicator (the left border) could be moved to the bottom instead?

Here's a few things I tried:

- Aligning the list item element with the logo text:
Screenshot from 2022-03-24 12-22-32

- Aligning the list item text with the logo text:
Screenshot from 2022-03-24 12-22-58

- Should we also align the left side of the search box with the logo text?
Screenshot from 2022-03-24 12-23-33

- Moving the active border to the bottom: 
Screenshot from 2022-03-24 12-30-35

- Moving the active border to the bottom and removing the left padding on the list item:
Screenshot from 2022-03-24 12-31-20

**Comment by clagom** [comment]
Hi, can we also have @marcushas to look at the size of the CoF as we briefly looked at it and seems small. If a bit larger it would also align better with Canonical

**Comment by lyubomir-popov** [comment]
@sowasred2012 sorry I forgot to include an active state, I'll add that and get backto you.

**Comment by lyubomir-popov** [comment]
@sowasred2012 how about this: line under the logo, then the rest of the lines indented
image

**Comment by sowasred2012** [comment]
Closing - as discussed in https://github.com/canonical-web-and-design/meeting-notes/issues/1025, dev work for the top nav logo is going to continue in Vanilla directly, and @bartaz and @bethcollins92 and co will use this as a starting point while the web tribe concentrates on the "All Canonical" dropdown content.

**Pull request closed without merging**
