### PR TITLE
New layout for career game results page

### LINKED ISSUE #353: [c.c career enhancements] Update the results page
[Brief](https://docs.google.com/document/d/1eXlLZKLmq_tLrOCgulbT4KYhsCq3FZ8AA7KX7L2jMeY/edit#)

Show a list of all departments, but ordered by department most jobs matching the user’s core skills.
Update the CTA on the department to be more specific, like ‘See 9 matching roles in Engineering >’

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- New layout for career game results page  
    - Top 4 jobs at the top in cards
    - List of jobs by department below
- Things to fix
    - The departments are still using the old ones like 'cloud engineering' which we hide from the user normally, I noticed it is visible on the live site as well in the department 'message'
    - image
    - These departments links don't lead to real pages
    - The list shows departments witout matching roles?
    - The bottom list doesn't exclude the top 4 roles
    - I don't invite someone to retake the test
    - The list is crazy long, so I truncated to 10 roles per department... not sure that's right

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/results?core-skills=Scientist%2CDeveloper%2COrganiser%2CAnalyzer%2CManager&filter=home-based&location=africa#available-roles
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Help fix the page...

## Issue / Card

Fixes #353 

## Screenshots
[truncated to 10 roles]

image

[all roles]
image

### CODE REVIEW

**Comment by cristinadresch** [comment]
@waynecrosby when can we expect designs for this one?

**Comment by waynecrosby** [comment]
@cristinadresch Going to look at it tomorrow if that's ok?

**Comment by waynecrosby** [comment]
@anthonydillon I've added some options to Zeplin, I think it would be nice if we could adopt a card style like in Charmhub where we can show how long the job has been active in the main 4 chosen roles. I have limited the amount of roles shown in each section below as it's a little overwhelming. I am not sure if we need to keep the roles for other disciplines too? If this is a targeted search we shouldn't be displaying roles in Finance and HR to an Engineer.

The Zeplin link is below, let me know your thoughts:
https://zpl.io/be9lM3W

**Comment by anthonydillon** [comment]
@pmahnke are you planning to fix up the links or want me to do it?

**Review by nottrobin — APPROVED** [review]

**Pull request merged**
