### PR TITLE
Update become a partner page

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Update become a partner page
- Add `/partners/thank-you` page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/become-a-partner
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare to [copy doc](https://docs.google.com/document/d/1Ihh9s3i72saCYaheXRVRn1Meg5lYN5U1gFbdvLMdWcc/edit)
- Go to `/partners/thank-you` and see the thank-you page. Note that the links on this page won't work properly as we have redirects to partners.ubuntu.com

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/2569

### CODE REVIEW

**Comment by waynecrosby** [comment]
@solazio Could you please update the page to match the below, thanks:
screencapture-canonical-com-canonical-web-and-design-pr-208-run-demo-haus-partners-thank-you-2020-04-20-12_29_31

Here is the illustration link:
https://assets.ubuntu.com/v1/0049554c-contact-us.svg

Cheers

**Comment by waynecrosby** [comment]
@solazio Looks good, but can you as a quick fix add some space below the text and illustration so that the footer is further down, I get a big white gap under it. Or, on shorter pages is there a way to anchor the footer to the base of the page?
Screenshot 2020-04-20 at 13 23 11

**Comment by solazio** [comment]
@waynecrosby we already have an [issue to fix that in vanilla](https://github.com/canonical-web-and-design/vanilla-framework/issues/1452), so I'll leave it to be fixed in vanilla as it affects more pages. Is the additional space needed in this case?

**Comment by waynecrosby** [comment]
@solazio Ok, you could maybe put a blank <div> with some &nbsp; in to cheat it down a bit but if not don't worry about it for now then.

**Pull request merged**
