### PR TITLE
Add rss feed for career section

### LINKED ISSUE #405: Add RSS feed for job openings
we should have an endpoint (eg. `canonical.com/careers/feed`) that lists all of the open jobs in an RSS format.

### PR DESCRIPTION
**Pull request by tbille**
## Done

- Add rss feed for careers sections

## QA

- Check out this feature branch
- Run the site using the command `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/feed
- You should get a feed with all the jobs open. Each job should have a link a description and a title

## Issue / Card

Fixes #405

### CODE REVIEW

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Code looks good but appears the output is not valid. Mainly missing meta information on the channel level:
image

**Comment by anthonydillon** [comment]
To test, paste the source of the RSS feed into https://validator.w3.org/feed/#validate_by_input

**Comment by tbille** [comment]
@anthonydillon nice one. I just updated the template. It is valid now.

**Review by anthonydillon — APPROVED** [review]
Excellent thank you!

Here is your badge:
image

**Pull request merged**
