### PR TITLE
Fixed add button on empty game card careers

### PR DESCRIPTION
**Pull request by iamarpitpatidar**
## Done
Hide `that's me` button on empty game card

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/start
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [EDIT: ] Oops! missed one step. select some cards and now click the empty cards.

## Screenshots
Actual Behavior on click after card selected. see the empty button 2nd card
Screenshot from 2021-04-03 13-02-24

Fixed to no button display at all.
Screenshot from 2021-04-03 13-07-42

### CODE REVIEW

**Comment by iamarpitpatidar** [comment]
ooh, one more thing, this update will also fix the mutiple selects of same skill.
Screenshot from 2021-04-03 13-33-30

**Comment by anthonydillon** [comment]
@iamarpitpatidar thank you very much for proposing this fix. I am unable to replicate this issue on both the latest Firefox and Chrome browsers.

This is what I see on master:
image

**Comment by iamarpitpatidar** [comment]
@anthonydillon once u select the card. like in your card you've select scienctist and developer. now click on the empty cards again. and there will the empty button and surprisingly u click those empty buttons it will even add the same skils again as shows in the image

**Review by anthonydillon — APPROVED** [review]
Awesome, thank you very much! :+1:

**Pull request merged**
